# Generated by Django 4.1 on 2024-01-24 19:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_vote_event_accounts_vote_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('event', 'account')},
        ),
    ]
