# Generated by Django 4.1 on 2024-01-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_remove_option_question'),
        ('questions', '0002_question_options_alter_question_event'),
        ('events', '0003_alter_vote_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterSelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='options.option')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voterselectedoption', to='events.vote')),
            ],
            options={
                'unique_together': {('vote', 'question')},
            },
        ),
    ]
