# Generated by Django 4.1 on 2024-01-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
    ]
