# Generated by Django 4.1 on 2024-01-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='emailconfirmationmodel',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
